apiVersion: v1
kind: Pod
metadata:
  name: initcont
spec:
  initContainers:
    - name: cc1
      image: ubuntu
      command: ["/bin/sh", "-c", "echo LIKE KARO DABAKE > /tmp/xchange/testfile; sleep 30"]
      volumeMounts:
        - name: xchange
          mountPath: "/tmp/xchange"
  containers:
    - name: cc2
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo cat /tmp/data/testfile ; sleep 5 ; done"]
      volumeMounts:
        - name: xchange
          mountPath: "/tmp/data"
  volumes:
    - name: xchange
      emptyDir: {}
