apiVersion: batch/v1
kind: Job
metadata:
  name: testjobb
spec:
  parallelism: 5                           # Runs for pods in parallel
  activeDeadlineSeconds: 10  # Timesout after 30 sec
  template:
    metadata:
      name: testjob
    spec:
      containers:
        - name: counter
          image: ubuntu
          command: ["bin/bash", "-c", "echo sahil; sleep 20"]
      restartPolicy: Never
