apiVersion: v1
kind: Pod
metadata:
  name: mylivenessprobe
  labels:
    test: liveness
spec:
  containers:
    - name: liveness
      image: busybox   # better than ubuntu for probes
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 1000
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5    # <-- must be inside livenessProbe
        periodSeconds: 5          # <-- same here
        timeoutSeconds: 30        # <-- same here
       
