apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
    - name: resource
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Sahil; sleep 5 ; done"]
      resources:                                          
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
